INSERT INTO PROCEDIMENTO_PACIENTE (
  NR_SEQUENCIA, NR_SEQ_ATEPACU, NR_ATENDIMENTO, DT_ENTRADA_UNIDADE, NR_SEQ_PROC_INTERNO,
  DT_PROCEDIMENTO, QT_PROCEDIMENTO, DT_ATUALIZACAO, NM_USUARIO,
  CD_CONVENIO, CD_CATEGORIA, CD_MEDICO, CD_PESSOA_FISICA,
  VL_PROCEDIMENTO, VL_MEDICO, VL_ANESTESISTA, VL_MATERIAIS,
  VL_AUXILIARES, VL_CUSTO_OPERACIONAL, TX_MEDICO, TX_ANESTESIA,
  CD_SENHA, DT_CONTA, CD_SETOR_ATENDIMENTO, IE_ORIGEM_PROCED,
  IE_VALOR_INFORMADO, CD_ESTABELECIMENTO_CUSTO, CD_TABELA_CUSTO,
  CD_SITUACAO_GLOSA, NR_INTERNO_CONTA, IE_EMITE_CONTA,
  CD_ESPECIALIDADE, IE_EMITE_CONTA_HONOR, CD_SETOR_RECEITA,
  VL_ADIC_PLANT, QT_PORTE_ANESTESICO, TX_HORA_EXTRA,
  IE_VIDEO, IE_DISPERSAO, CD_SETOR_PACIENTE, CD_FUNCAO, CD_PERFIL
)
SELECT
  PROCEDIMENTO_PACIENTE_SEQ.NEXTVAL,   -- ✅ sequence correta
  PP.NR_SEQ_ATEPACU,
  PP.NR_ATENDIMENTO,
  PP.DT_ENTRADA_UNIDADE,
  13444,  -- ✅ substituindo o 13368
  PP.DT_PROCEDIMENTO,
  1,
  SYSDATE,
  PP.NM_USUARIO,
  PP.CD_CONVENIO,
  PP.CD_CATEGORIA,
  PP.CD_MEDICO,
  PP.CD_PESSOA_FISICA,
  0, 0, 0, 0, 0, 0, 0, 0,
  PP.CD_SENHA,
  PP.DT_CONTA,
  PP.CD_SETOR_ATENDIMENTO,
  PP.IE_ORIGEM_PROCED,
  PP.IE_VALOR_INFORMADO,
  PP.CD_ESTABELECIMENTO_CUSTO,
  PP.CD_TABELA_CUSTO,
  PP.CD_SITUACAO_GLOSA,
  PP.NR_INTERNO_CONTA,
  PP.IE_EMITE_CONTA,
  PP.CD_ESPECIALIDADE,
  PP.IE_EMITE_CONTA_HONOR,
  PP.CD_SETOR_RECEITA,
  PP.VL_ADIC_PLANT,
  PP.QT_PORTE_ANESTESICO,
  PP.TX_HORA_EXTRA,
  PP.IE_VIDEO,
  PP.IE_DISPERSAO,
  PP.CD_SETOR_PACIENTE,
  PP.CD_FUNCAO,
  PP.CD_PERFIL
FROM PROCEDIMENTO_PACIENTE PP

  where PP.NR_SEQ_PROC_INTERNO = 13368
  AND DT_PROCEDIMENTO BETWEEN '01/10/2025' AND '31/10/2025'
AND obter_estab_atendimento(NR_ATENDIMENTO) = 4
AND CD_CONVENIO = 7 
AND PP.NR_INTERNO_CONTA <> 176186
;
